version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:261358762045:task-definition/mywebapi-task:2
        LoadBalancerInfo:
          ContainerName: mywebapi-container
          ContainerPort: 8080